// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kadaster
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class KadastraalOnroerendeZaak : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""KadastraalOnroerendeZaak"",""namespace"":""Kadaster"",""fields"":[{""name"":""Id"",""type"":""long""},{""name"":""Type"",""type"":{""type"":""enum"",""name"":""KadastraalOnroerendeZaakType"",""namespace"":""Kadaster"",""symbols"":[""Apartementsrecht"",""Perceel""]}},{""name"":""KadastraleAanduiding"",""type"":{""type"":""record"",""name"":""KadastraleAanduiding"",""namespace"":""Kadaster"",""fields"":[{""name"":""AppartementsrechtVolgnummer"",""type"":[""null"",""int""]},{""name"":""KadastraleGemeenteCode"",""type"":""int""},{""name"":""Perceelnummer"",""type"":""int""},{""name"":""Sectie"",""type"":""string""}]}},{""name"":""Koopsom"",""type"":{""type"":""record"",""name"":""Koopsom"",""namespace"":""Kadaster"",""fields"":[{""name"":""Bedrag"",""type"":""long""},{""name"":""Koopjaar"",""type"":""int""},{""name"":""IndicatieMetMeerObjectenVerkregen"",""type"":""boolean""}]}},{""name"":""ZakelijkGerechtigden"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""ZakelijkGerechtigde"",""namespace"":""Kadaster"",""fields"":[{""name"":""Id"",""type"":""long""},{""name"":""Type"",""type"":{""type"":""enum"",""name"":""ZakelijkGerechtigdeType"",""namespace"":""Kadaster"",""symbols"":[""Beklemrechthouder"",""Eigenaar"",""Erfpachter"",""GebruikBewoning"",""Grondrente"",""Opstalhouder"",""Vaderlandsrecht"",""Stadsmeierrecht"",""Vruchtgebruiker"",""ErfpachterOpstalhouder"",""Nutsvoorzieningen"",""TweeBelastingen"",""BelastingDerde"",""Bprecht"",""NutsvoorzieningenGedeelte"",""Artikel5_3b""]}},{""name"":""Aanvangsdatum"",""type"":""long"",""logicalType"":""date""}]}}}]}");
		private long _Id;
		private Kadaster.KadastraalOnroerendeZaakType _Type;
		private Kadaster.KadastraleAanduiding _KadastraleAanduiding;
		private Kadaster.Koopsom _Koopsom;
		private IList<Kadaster.ZakelijkGerechtigde> _ZakelijkGerechtigden;
		public virtual Schema Schema
		{
			get
			{
				return KadastraalOnroerendeZaak._SCHEMA;
			}
		}
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public Kadaster.KadastraalOnroerendeZaakType Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				this._Type = value;
			}
		}
		public Kadaster.KadastraleAanduiding KadastraleAanduiding
		{
			get
			{
				return this._KadastraleAanduiding;
			}
			set
			{
				this._KadastraleAanduiding = value;
			}
		}
		public Kadaster.Koopsom Koopsom
		{
			get
			{
				return this._Koopsom;
			}
			set
			{
				this._Koopsom = value;
			}
		}
		public IList<Kadaster.ZakelijkGerechtigde> ZakelijkGerechtigden
		{
			get
			{
				return this._ZakelijkGerechtigden;
			}
			set
			{
				this._ZakelijkGerechtigden = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Type;
			case 2: return this.KadastraleAanduiding;
			case 3: return this.Koopsom;
			case 4: return this.ZakelijkGerechtigden;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.Type = (Kadaster.KadastraalOnroerendeZaakType)fieldValue; break;
			case 2: this.KadastraleAanduiding = (Kadaster.KadastraleAanduiding)fieldValue; break;
			case 3: this.Koopsom = (Kadaster.Koopsom)fieldValue; break;
			case 4: this.ZakelijkGerechtigden = (IList<Kadaster.ZakelijkGerechtigde>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
