// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kadaster
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class KadastraleAanduiding : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""KadastraleAanduiding"",""namespace"":""Kadaster"",""fields"":[{""name"":""AppartementsrechtVolgnummer"",""type"":[""null"",""int""]},{""name"":""KadastraleGemeenteCode"",""type"":""int""},{""name"":""Perceelnummer"",""type"":""int""},{""name"":""Sectie"",""type"":""string""}]}");
		private System.Nullable<int> _AppartementsrechtVolgnummer;
		private int _KadastraleGemeenteCode;
		private int _Perceelnummer;
		private string _Sectie;
		public virtual Schema Schema
		{
			get
			{
				return KadastraleAanduiding._SCHEMA;
			}
		}
		public System.Nullable<int> AppartementsrechtVolgnummer
		{
			get
			{
				return this._AppartementsrechtVolgnummer;
			}
			set
			{
				this._AppartementsrechtVolgnummer = value;
			}
		}
		public int KadastraleGemeenteCode
		{
			get
			{
				return this._KadastraleGemeenteCode;
			}
			set
			{
				this._KadastraleGemeenteCode = value;
			}
		}
		public int Perceelnummer
		{
			get
			{
				return this._Perceelnummer;
			}
			set
			{
				this._Perceelnummer = value;
			}
		}
		public string Sectie
		{
			get
			{
				return this._Sectie;
			}
			set
			{
				this._Sectie = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.AppartementsrechtVolgnummer;
			case 1: return this.KadastraleGemeenteCode;
			case 2: return this.Perceelnummer;
			case 3: return this.Sectie;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.AppartementsrechtVolgnummer = (System.Nullable<int>)fieldValue; break;
			case 1: this.KadastraleGemeenteCode = (System.Int32)fieldValue; break;
			case 2: this.Perceelnummer = (System.Int32)fieldValue; break;
			case 3: this.Sectie = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
