// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kadaster
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public enum ZakelijkGerechtigdeType
	{
		Beklemrechthouder,
		Eigenaar,
		Erfpachter,
		GebruikBewoning,
		Grondrente,
		Opstalhouder,
		Vaderlandsrecht,
		Stadsmeierrecht,
		Vruchtgebruiker,
		ErfpachterOpstalhouder,
		Nutsvoorzieningen,
		TweeBelastingen,
		BelastingDerde,
		Bprecht,
		NutsvoorzieningenGedeelte,
		Artikel5_3b,
	}
}
