openapi: 3.0.0
info:
  title: "BRK events bevragen API"
  description: |
    API voor het bevragen van BRK events op basis van
    - kadastraal onroerende zaak identificatie
    - kadastrale aanduiding
    - zakelijk gerechtigde identificatie
    - stuk identificatie
    - kadastraal onroerende zaak event identificatie
  version: "1.0.0"
tags:
    - name: kadastraal onroerende zaak events
paths:
  /kadastraalonroerendezaakevents:
    get:
      operationId: GetKadastraalOnroerendeZaakEvents
      tags:
          - "kadastraal onroerende zaak events"
      description: |
        Ophalen van kadastraal onroerende zaak events op basis van
        - kadastraalonroerendezaakidentificatie of
        - stukidentificatie of
        - zakelijkgerechtigdeidentificatie of
        - kadastraleaanduiding en
        - de **vanafTijdstip** tijdstip of
        - de event met de **vanafEventIdentificatie** identificatie

        Met de **inclusiefVorigToestand** parameter wordt aangegeven of de vorige toestand van de kadastraal onroerende zaak moet worden opgehaald
      parameters:
        - name: kadastraalonroerendezaakidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: stukidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: zakelijkgerechtigdeidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: kadastraleaanduiding
          description: |
            Kadastrale aanduiding is een unieke aanduiding van een onroerende zaak. De volgorde waarin deze string wordt opgebouwd is
            - [Kadastrale gemeente](http://www.kadaster.nl/schemas/waardelijsten/KadastraleGemeente/).
            - sectie, 1 of 2 hoofdletters
            - perceelnummer, 1 tot 5 cijfers
            - appartementsrechtVolgnummer, Hoofdletter A gevolgd door 1 tot 4 cijfers (optioneel)
          in: query
          required: false
          schema:
            type: string
            pattern: "^([a-zA-Z0-9'][a-zA-Z0-9' ,-]*[a-zA-Z0-9]) ([A-IK-Z]{1,2}) ([1-9][0-9]{0,4})( A[1-9][0-9]{0,3})?$"
            example: "'s Gravenhage C 1277 A3"
        - name: vanafTijdstip
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: vanafEventIdentificatie
          in: query
          required: false
          schema:
            type: string
        - name: inclusiefVorigToestand
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: events gevonden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KadastraalOnroerendeZaakEvents"
  /kadastraalonroerendezaakevents/{identificatie}:
    get:
      operationId: GetKadastraalOnroerendeZaakEvent
      tags:
          - "kadastraal onroerende zaak events"
      description: |
        Ophalen van een kadastraal onroerende zaak event op basis van zijn identificatie

        Met de expand parameter wordt aangegeven of de vorige toestand van de kadastraal onroerende zaak moet worden opgehaald
      parameters:
        - name: identificatie
          in: path
          required: true
          schema:
            type: string
        - name: inclusiefVorigToestand
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: event gevonden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KadastraalOnroerendeZaakEvent"
components:
  schemas:
    KadastraalOnroerendeZaakEvents:
      type: object
      properties:
        volgendEventIdentificatie:
          description: |
            De identificatie van het volgende event.  
            Deze bevat geen waarde als er op het moment van de bevraging geen volgende events zijn
          type: string
        volgendeEventsLink:
          description: |
            De url waarmee de volgende events vanaf de event met identificatie = volgendEventIdentificatie kan worden bevraagd.
            Deze bevat geen waarde als er op het moment van de bevraging geen volgende events zijn
          type: string
        events:
          type: array
          items:
            $ref: "#/components/schemas/KadastraalOnroerendeZaakEvent"
    KadastraalOnroerendeZaakEvent:
      type: object
      description: |
        - vorigEventLink bevat een link waarmee de vorige KadastraalOnroerendeZaakEvent kan worden opgehaald
        - vorigToestandKadastraalOnroerendeZaak wordt alleen gevuld als expand=true
      properties:
        identificatie:
          description: unieke identifier van een kadastraal onroerende zaak event
          type: string
        tijdstip:
          description: creatie tijdstip van event
          type: string
          format: date-time
        indicatieStukCompleet:
          description: true als alle stukdelen behorende bij de stuk aanwezig zijn t.b.v. het beoordelen van samenhangend geheel
          type: boolean
        vorigEventLink:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Href"
        vorigToestandKadastraalOnroerendeZaak:
          $ref: "#/components/schemas/KadastraalOnroerendeZaakMutatie"
        nieuweToestandKadastraalOnroerendeZaak:
          $ref: "#/components/schemas/KadastraalOnroerendeZaakMutatie"
    KadastraalOnroerendeZaakMutatie:
      allOf:
      - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/v1.1.1/specificatie/genereervariant/openapi.yaml#/components/schemas/KadastraalOnroerendeZaak"
      properties:
        adressen:
          type: array
          items: 
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/v1.1.1/specificatie/genereervariant/openapi.yaml#/components/schemas/Adres"
        zakelijkGerechtigden:
          type: array
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/v1.1.1/specificatie/genereervariant/openapi.yaml#/components/schemas/ZakelijkGerechtigde"
