openapi: 3.0.0
info:
  title: "BRK events bevragen API"
  version: "1.0.0"
paths:
  /abonnement/kadastraalonroerendezaakevents:
    get:
      description: |
        Ophalen van nieuwe kadastraal onroerende zaak events.  
        Het resultaat kan worden gefilterd op basis van
        - één of meerdere topics
        - de van tijdstip
        - de van en tot tijdstip

        Met de expand parameter wordt aangegeven of de vorige toestand van de kadastraal onroerende zaak moet worden opgehaald
      parameters:
        - name: topics
          in: query
          required: false
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: van
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: tot
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: expand
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: events gevonden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KadastraalOnroerendeZaakEvents"
  /kadastraalonroerendezaakevents:
    get:
      description: |
        Ophalen van kadastraal onroerende zaak events op basis van
        - kadastraalonroerendezaakidentificatie
        - stukidentificatie
        - zakelijkgerechtigdeidentificatie
        - kadastraleaanduiding
        - de van tijdstip
        - de van en tot tijdstip

        Verplicht: Eén van de drie identificatie parameters of de kadastrale aanduiding parameter
        
        Met de expand parameter wordt aangegeven of de vorige toestand van de kadastraal onroerende zaak moet worden opgehaald
      parameters:
        - name: kadastraalonroerendezaakidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: stukidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: zakelijkgerechtigdeidentificatie
          in: query
          required: false
          schema:
            type: string
        - name: kadastraleaanduiding
          description: |
            Kadastrale aanduiding is een unieke aanduiding van een onroerende zaak. De volgorde waarin deze string wordt opgebouwd is
            - [Kadastrale gemeente](http://www.kadaster.nl/schemas/waardelijsten/KadastraleGemeente/).
            - sectie, 1 of 2 hoofdletters
            - perceelnummer, 1 tot 5 cijfers
            - appartementsrechtVolgnummer, Hoofdletter A gevolgd door 1 tot 4 cijfers (optioneel)
          in: query
          required: false
          schema:
            type: string
            pattern: "^([a-zA-Z0-9'][a-zA-Z0-9' ,-]*[a-zA-Z0-9]) ([A-IK-Z]{1,2}) ([1-9][0-9]{0,4})( A[1-9][0-9]{0,3})?$"
            example: "'s Gravenhage C 1277 A3"
        - name: van
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: tot
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: expand
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: events gevonden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KadastraalOnroerendeZaakEvents"
  /kadastraalonroerendezaakevents/{identificatie}:
    get:
      description: |
        Ophalen van een kadastraal onroerende zaak event op basis van zijn identificatie

        Met de expand parameter wordt aangegeven of de vorige toestand van de kadastraal onroerende zaak moet worden opgehaald
      parameters:
        - name: identificatie
          in: path
          required: true
          schema:
            type: string
        - name: expand
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: event gevonden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KadastraalOnroerendeZaakEvent"
components:
  schemas:
    KadastraalOnroerendeZaakEvents:
      type: array
      items:
        $ref: "#/components/schemas/KadastraalOnroerendeZaakEvent"
    KadastraalOnroerendeZaakEvent:
      type: object
      description: |
        - vorigEventLink bevat een link waarmee de vorige KadastraalOnroerendeZaakEvent kan worden opgehaald
        - vorigToestandKadastraalOnroerendeZaak wordt alleen gevuld als expand=true
      properties:
        identificatie:
          description: unieke identifier van een kadastraal onroerende zaak event
          type: string
        tijdstip:
          description: creatie tijdstip van event
          type: string
          format: date-time
        indicatieStukCompleet:
          description: true als alle stukdelen behorende bij de stuk aanwezig zijn t.b.v. het beoordelen van samenhangend geheel
          type: boolean
        vorigEventLink:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Href"
        vorigToestandKadastraalOnroerendeZaak:
          $ref: "#/components/schemas/KadastraalOnroerendeZaakMutatie"
        nieuweToestandKadastraalOnroerendeZaak:
          $ref: "#/components/schemas/KadastraalOnroerendeZaakMutatie"
    KadastraalOnroerendeZaakMutatie:
      allOf:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/KadastraalOnroerendeZaak"
      properties:
        adressen:
          type: array
          items: 
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/Adres"
        zakelijkGerechtigden:
          type: array
          items:
            $ref: "#/components/schemas/ZakelijkGerechtigdeMutatie"
        stukken:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/AangebodenStuk"
        onroerendeZaakFiliatie:
          type: "array"
          description: "Dit is een link naar filiaties die deze Kadastraal Onroerende Zaak betreffen."
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/OnroerendeZaakFiliatie"
        voorwaartseOnroerendeZaakFiliatie:
          type: "array"
          description: "Dit is een link naar filiaties waarbij deze Kadastraal Onroerende Zaak overgegaan in een andere KadastraalOnroerendeZaak."
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/VoorwaartseOnroerendeZaakFiliatie"
        publiekrechtelijkeBeperkingen:
          type: "array"
          description: "Dit is een link naar filiaties waarbij deze Kadastraal Onroerende Zaak overgegaan in een andere KadastraalOnroerendeZaak."
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/PubliekrechtelijkeBeperking"

    ZakelijkGerechtigdeMutatie:
      allOf:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/ZakelijkGerechtigde"
      properties:
        stukken:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/AangebodenStuk"
        stukdelen:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/BRKBevragen1.1/specificatie/BRK-Bevragen/openapi.yaml#/components/schemas/Stukdeel"
